development:
  adapter: postgresql
  encoding: unicode
  database: bandits_development
  pool: 5
  username: Matt
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: bandits_test
  pool: 5
  username: Matt
  password: 